plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.143'
    id 'idea'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

repositories {
    maven { url = 'https://maven.blamejared.com' }
    maven { url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/' }
    maven { url = 'https://maven.theillusivec4.top/' }
}

dependencies {
    implementation ("com.hollingsworth.ars_nouveau:ars_nouveau-1.21.1:5.13.0.1392") {
        transitive = false
    }
    implementation "software.bernie.geckolib:geckolib-neoforge-1.21.1:4.9.2"
    implementation "top.theillusivec4.curios:curios-neoforge:9.5.1+1.21.1"
    runtimeOnly "mezz.jei:jei-1.21.1-neoforge:19.43.0.395"
    compileOnly "com.hollingsworth.nuggets:nuggets-neoforge-1.21.1:1.1.0.48"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
            programArguments.addAll('--username', 'Steve')
        }
        server {
            server()
            programArgument '--nogui'
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
sourceSets.main.resources.srcDir generateModMetadata

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}